  - name: install packages
    package:
      name:
        - htop
        - expect
        - inxi
        - xrandr
        - tmux
        - vim
        - tree
        - nmap
        - btrfs-assistant
        - fastfetch
        - gnome-tweaks
        - gnome-shell-extension-dash-to-dock
        - gnome-shell-extension-system-monitor

  - name: Install dnf-plugins-core
    dnf:
      name: dnf-plugins-core
      state: present

#  - name: Add Brave browser repository
#    become: true
#    command: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
#
#  - name: Import Brave browser GPG key
#    rpm_key:
#      key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
#      state: present
#
#  - name: Install Brave browser
#    dnf:
#      name: brave-browser
#      state: present

  - name: Install Flatpak
    package:
      name: flatpak
      state: present

  - name: Add Flathub repository
    command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  - name: Install Zoom
    command: flatpak install -y flathub us.zoom.Zoom


  - name: install Extension Manager via Flatpak
    become: true
    command: flatpak install -y flathub com.mattjakeman.ExtensionManager

  - name: copy wallpaper file
    copy: 
      src: files/Sci-milkyway.png
      dest: /home/brett/Pictures/Sci-milkyway.png
      owner: brett
      group: brett

  - name: set wallpaper
    become_user: brett
    command: gsettings set org.gnome.desktop.background picture-uri 'file:///home/brett/Pictures/Sci-milkyway.png'
  
  - name: set wallpaper position
    become_user: brett
    command: gsettings set org.gnome.desktop.background picture-options 'zoom'

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/brett/.bashrc
      owner: brett
      group: brett

  - name: copy bash_aliases file
    copy:
      src: files/bash_aliases
      dest: /home/brett/.bash_aliases
      owner: brett
      group: brett

  - name: set up sudo for user brett
    copy:
      src: files/sudoer_brett
      dest: /etc/sudoers.d/brett
      owner: root
      group: root
      mode: 0440

  - name: enable Extension Manager
    become_user: brett
    command: flatpak run com.mattjakeman.ExtensionManager enable extension-manager@pew.worldwidemann.com

  - name: enable Dash to Dock
    become_user: brett
    command: gnome-extensions enable dash-to-dock@micxgx.gmail.com

  - name: enable System Monitor Next
    become_user: brett
    command: gnome-extensions enable system-monitor-next@paradoxxx.zero.gmail.com
