- name: Configure network
  hosts: fedora_laptop
  become: true

  tasks:
    - name: Configure network interface
      network: state=up method=manual ip={{ ansible_host }} netmask=255.255.255.0 gateway=192.168.1.1

    - name: Create DNS records
      systemd_resolved: name=local addresses=8.8.8.8
