# Ansible installed User specific aliases and functions
set -o vi
#alias update='sudo apt update;sudo apt upgrade'
alias update='sudo dnf update'
alias u='uptime ; uname -r ; rpm -q kernel'
#alias list='apt list --upgradable'
alias lsd='ls -d */'

